### ISSUE TITLE
Typo in documentation (Job tracking)

### ISSUE THREAD

**Issue by GBoGH** [CESNET/metacentrum-user-docs#39]
On https://docs.metacentrum.cz/computing/jobs/job-tracking/#output-of-running-jobs there is a typo in `$SCRATCHDIR`, the T is missing
![image](https://github.com/user-attachments/assets/c199b5fe-b57a-4e5f-be60-fdb35ff6d64d)

**Comment by jirivorel** [comment]
Thanks for letting us know. Fixed.
